POST http://localhost:5000/api/url/shorten
Content-Type: application/json

{
    "longUrl": "https://www.amazon.com/gp/product/B00MH4QM1S/ref=pd_alm_hps_1_3_fs_dsk_cp_mw_img?fpw=alm&almBrandId=QW1hem9uIEZyZXNo&pd_rd_r=1f1e1611-2d4a-44cb-8ab8-a050c3751d33&pd_rd_w=1eDM7&pd_rd_wg=RF84U&pd_rd_i=B00MH4QM1S&pf_rd_r=XF1665JV2GTGPZXAGVAP&pf_rd_p=421231a6-4bf6-48be-a4e7-e1171fbc0533"
}

